services:
  - type: web
    name: daily-task-bot
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
    healthCheckPath: /
    autoDeploy: true
    plan: free 